document.addEventListener("DOMContentLoaded", function () {
    const container = document.querySelector(".container");
    
    const tilesData = [
        { title: "Allergy, Asthma and TB treatmen", desc: "At The Chest Clinic in Pune, we offer specialized treatment for  allergies, asthma, and tuberculosis with a focus on comprehensive,  patient-centered care. Our experienced team uses the latest diagnostic  tools and treatment techniques to manage and alleviate symptoms  effectively. For allergies, we provide detailed assessments to identify  triggers and create customized management plans. Our asthma care  includes advanced therapies and patient education to help you manage and reduce asthma attacks. In tuberculosis treatment, we employ proven  protocols and regular monitoring to ensure successful outcomes. At The  Chest Clinic, our commitment is to your respiratory health, offering  compassionate care and ongoing support to improve your quality of life.", img: "https://via.placeholder.com/300/FF5733" },
        { title: "Endobronchial Ultrasound", desc: "At The Chest Clinic in Pune, our Endobronchial Ultrasound (EBUS) service provides cutting-edge diagnostic capabilities for lung diseases. EBUS  is a minimally invasive technique that combines endoscopy and ultrasound to visualize and biopsy abnormal tissues within the lungs and  surrounding lymph nodes. This advanced procedure is instrumental in  accurately diagnosing conditions such as lung cancer, infections, and  inflammatory diseases. With real-time imaging, EBUS allows for precise  targeting of biopsies, enhancing diagnostic accuracy and reducing the  need for more invasive procedures. Our experienced team ensures a  comfortable experience, focusing on delivering comprehensive care and  clear results. At The Chest Clinic, we are dedicated to using the latest technology to provide top-quality care and support for our patients.", img: "https://via.placeholder.com/300/33FF57" },
        { title: "Bronchoscopy Services", desc: "At The Chest Clinic in Pune, we offer comprehensive bronchoscopy  services designed for accurate diagnosis and effective treatment of  respiratory conditions. Our advanced bronchoscopy procedures allow for  detailed examination of the airways and lungs, enabling us to identify  and address issues such as infections, tumors, and chronic obstructive  pulmonary disease (COPD).Our team of highly skilled  pulmonologists uses state-of-the-art technology to perform both  diagnostic and therapeutic bronchoscopy. We are committed to providing a comfortable and supportive environment for our patients, ensuring their well-being throughout the procedure. With a focus on personalized care, we tailor our approach to meet each patient’s unique needs, aiming for  the best possible outcomes. Whether you require a  routine check-up or specialized treatment, The Chest Clinic is dedicated to supporting your respiratory health with expertise and compassion.  Trust us to deliver the highest standard of care in bronchoscopy  services.", img: "https://via.placeholder.com/300/3357FF" },
        { title: "Thoracoscopy services", desc: "At The  Chest Clinic in Pune, we provide cutting-edge thoracoscopy services, a  state-of-the-art, minimally invasive technique designed for  comprehensive evaluation and treatment of chest conditions.  Thoracoscopy, also known as video-assisted thoracic surgery (VATS),  involves inserting a small camera and specialized instruments through  tiny incisions in the chest. This advanced procedure allows our skilled  pulmonologists to inspect the lungs, pleura, and other thoracic  structures with exceptional precision.Thoracoscopy is  utilized for diagnosing and managing various conditions such as lung  tumors, infections, and pleural diseases. It offers significant benefits over traditional open surgery, including reduced pain, shorter recovery time, and minimal scarring. Our clinic is equipped with the latest  technology and adheres to the highest standards of care to ensure  optimal outcomes. Trust The Chest Clinic for expert thoracoscopy  services tailored to your needs, delivering effective treatment while  prioritizing your comfort and well-being.", img: "https://via.placeholder.com/300/57FF33" },
        { title: "Cardiac Care", desc: "The Chest  Clinic in Pune provides specialized Cardiac Care services, catering to a wide range of heart-related conditions with a patient-centered  approach. Our expert cardiologists and healthcare team are dedicated to  offering comprehensive cardiac care, including prevention, diagnosis,  and treatment of heart diseases. We specialize in managing high blood  pressure, coronary artery disease, heart failure, arrhythmias, and  more. With advanced diagnostic tools, such as ECG,  echocardiography, and stress tests, we ensure precise and timely  detection of heart issues. Our personalized treatment plans include  lifestyle modifications, medications, and interventional procedures like angioplasty and stenting when necessary. At The Chest Clinic, we  emphasize preventive care through regular screenings and health  education to help our patients maintain optimal heart health. Whether  you need a routine check-up or advanced treatment, our dedicated team is here to support your journey towards a healthier heart with compassion  and excellence in care.", img: "https://via.placeholder.com/300/FF33A1" },
        { title: "Diabetes Managementes", desc: "At The  Chest Clinic in Pune, we understand that managing diabetes requires a  personalized and comprehensive approach. Our diabetes management  services are designed to help patients effectively control their blood  sugar levels, prevent complications, and lead healthier lives. With a  team of experienced doctors and specialists, we provide tailored care  plans that address each patient's unique needs.Our  clinic offers thorough consultations, advanced monitoring, and regular  follow-ups to ensure optimal diabetes control. We focus on early  detection and continuous management to minimize the risks of  complications, such as heart disease, kidney problems, and nerve damage.In addition to medical treatment, we emphasize lifestyle modifications,  including nutrition counseling, exercise guidance, and stress  management, to promote overall well-being. Whether you're newly  diagnosed or looking for better control of your condition, The Chest  Clinic provides compassionate and expert care to help you manage  diabetes with confidence and improve your quality of life.", img: "https://via.placeholder.com/300/33A1FF" },
        { title: "Chest Diseases Treatment", desc: "The Chest Clinic in Pune specializes in the diagnosis and treatment of a wide range of chest diseases, including asthma, Chronic Obstructive  Pulmonary Disease (COPD), tuberculosis, bronchitis, pneumonia, and other respiratory infections. With a team of experienced pulmonologists and  state-of-the-art facilities, the clinic offers personalized care to  patients suffering from both acute and chronic respiratory conditions.  The Chest Clinic provides advanced diagnostic services, including  pulmonary function tests, chest X-rays, and allergy testing, ensuring  accurate and timely treatment plans. Patients receive comprehensive  care, from medical management and lifestyle guidance to specialized  therapies like bronchoscopy and spirometry. The clinic’s focus on  patient well-being, combined with a commitment to using the latest  medical advancements, ensures effective and compassionate treatment for  respiratory health. Whether managing long-term conditions or addressing  new symptoms, The Chest Clinic delivers expert care for optimal lung  health and overall wellness.", img: "https://via.placeholder.com/300/A133FF" },
        { title: "Micro Laryngeal Surgeries", desc: "At Chest  Clinic, Pune, Micro Laryngeal Surgeries are advanced, minimally invasive procedures designed to treat a range of vocal cord and laryngeal  disorders. Utilizing state-of-the-art microscopes and precision  instruments, these surgeries allow for accurate treatment of conditions  such as vocal cord nodules, polyps, cysts, and early-stage cancers of  the larynx. The procedure is performed under general anesthesia and  involves the use of a laryngoscope to access the vocal cords without any external incisions.Micro Laryngeal Surgeries at Chest Clinic prioritize patient comfort and faster recovery. With reduced  tissue trauma, patients can expect shorter hospital stays, quicker  recovery times, and minimal scarring. These surgeries also enhance voice quality by preserving as much of the healthy tissue as possible.  Whether addressing benign growths, lesions, or other laryngeal  abnormalities, the expert team at Chest Clinic provides personalized  care to ensure the best possible outcomes for each patient.", img: "https://via.placeholder.com/300/FFA133" },
        { title: "Hearing Aid Center", desc: "The Hearing Aid Center at Chest Clinic, Pune, is dedicated to providing  comprehensive audiological care to improve hearing health and enhance  quality of life. Our center offers a wide range of advanced hearing  aids, from discreet in-ear models to powerful behind-the-ear devices,  all designed to meet individual needs. Our experienced audiologists  conduct thorough hearing assessments to determine the most suitable  hearing solutions for each patient. We focus on personalized  consultations, ensuring that each patient receives expert guidance on  the best hearing aids for their lifestyle, hearing loss severity, and  budget.At the Hearing Aid Center, we are committed to  delivering high-quality service from the initial assessment to fitting  and beyond. We offer ongoing support, including hearing aid adjustments, maintenance, and repair services, to ensure optimal performance. Our  goal is to provide solutions that are comfortable, effective, and  tailored to help patients hear more clearly and live more confidently.  Visit us at Chest Clinic, Pune, for professional hearing care you can  trust.", img: "https://via.placeholder.com/300/FF3380" },
        { title: "Head and neck Surgeries", desc: "At The Chest Clinic in Pune, we offer comprehensive care for head and  neck surgeries, addressing a wide range of conditions with expertise and precision. Our dedicated team of specialists is equipped with the  latest technology and surgical techniques to handle complex cases,  including tumors, cysts, and structural abnormalities. We prioritize  patient safety and comfort, ensuring that each procedure is tailored to  individual needs. From diagnostic evaluations to advanced surgical  interventions, our approach integrates cutting-edge treatments with  compassionate care. Our goal is to achieve optimal outcomes while  providing supportive and personalized treatment throughout the recovery  process. At The Chest Clinic, your health and well-being are our top  priorities.", img: "https://via.placeholder.com/300/33FFDD" }
    ];
    
    container.innerHTML = ""; // Clear any existing tiles before adding new ones
    
    tilesData.forEach(data => {
        const tile = document.createElement("div");
        tile.classList.add("tile");
        
        tile.innerHTML = `
            <div class="tile-content">
                <img src="${data.img}" alt="${data.title}">
                <div class="caption">
                    <h3>${data.title}</h3>
                    <p class="short-content">${data.desc.substring(0, 100)}...</p>
                    <p class="extra-content" style="display: none;">${data.desc}</p>
                    <a href="#" class="view-more" onclick="toggleContent(this); return false;">View More</a>
                </div>
            </div>
        `;
        
        container.appendChild(tile);
    });
  });
  
  function toggleContent(link) {
    const shortContent = link.previousElementSibling.previousElementSibling;
    const extraContent = link.previousElementSibling;
    
    if (extraContent.style.display === "none" || extraContent.style.display === "") {
        shortContent.style.display = "none";
        extraContent.style.display = "block";
        link.textContent = "View Less";
    } else {
        shortContent.style.display = "block";
        extraContent.style.display = "none";
        link.textContent = "View More";
    }
  }
  